### ISSUE TITLE
Trouble using the library

### ISSUE THREAD

**Issue by thedim-witted** [particle-iot/lwip#5]
Hi, I want to use mDNS in my particle photon and use it the resolve the IP of a host from its .local domain name. I found that this library has some functionality in support of that but I couldn't find enough instructions on how to use it.
I am using an offline toolchain to compile my programs. And I am not sure how to call or include this library in the code. The instructions in the code are not very helpful and also there are no comments in the code to figure out.

**Comment by thedim-witted** [comment]
Anyone anything?

**Comment by avtolstoy** [comment]
LwIP is a TCP/IP stack implementation. It is used on a Photon but it's within proprietary WICED TCP/IP stack and it builds a lot of things on top, same with DeviceOS.

It'd be best to find a proper library that uses higher level sockets to do this.
